version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - run:
          name: Build
          command: cd java && ./gradlew assemble
      - run:
          name: Publish
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" && -n "${CIRCLE_TAG}" ]; then
              cd java && ./gradlew publishToSonatype closeSonatypeStagingRepository
            fi
workflows:
  version: 2
  workflow:
    jobs:
      - build
